[package]
name = "druid-admin-widgets"
version = "0.1.0"
authors = ["Carlos Eduardo Melo <ceduardo.melo@redime.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
